### PR TITLE
SLING-10624: Callback when SlingRepository init fails

### PR DESCRIPTION
**Pull request by mreutegg**

### CODE REVIEW

**Comment by bdelacretaz** [comment]
I would prefer `stoppingOnError`as the method name if that works for you, I think that's really what's happening.

Also, it would be good to provide tests for that new feature. The `RepositoryInitializersTest` does cause the first error-triggered stop() to be called, and I suppose throwing an exception in `create` would call the other one.

**Comment by mreutegg** [comment]
> I would prefer stoppingOnErroras the method name if that works for you

Sure, that works for me. I'm not particularly good at naming things ;)

I added a test. Let's see if Sonar is happy now. Funny enough, that part of the code was not covered before either.

**Comment by mreutegg** [comment]
@bdelacretaz, WDYT? Is this ready to merge?

**Comment by bdelacretaz** [comment]
I won't be able to merge this myself before Wednesday but if someone wants to do that I'm fine.

**Comment by stefan-egli** [comment]
Looks like the concerns have been addressed and things look fine for me. Merging.

**Pull request merged**
